apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/Omriyakubovsky/CI-React.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{path.basenames}}'
    spec:
      project: defaultddddssss
      source:
        repoURL: https://github.com/Omriyakubovsky/CI-Refact.git
        targetRevision: HEeeAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            goldilocks.fairwinds.com/enabled: true
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true