apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: service-react-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: react-app