apiVersion: apps/v1
kind: Deployment
metadata:
  name: "website-deployment"
spec:
  selector:
    matchLabels:
      app: "website"
  replicas: 1
  template:
    metadata:
      labels:
        app: "website"
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: "website"
        ports:
        - containerPort: 80