name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and create release
        run: |
          # Bump version
          currentTag=$(git describe --abbrev=0 --tags --always)
          if [[ -z "$currentTag" ]]; then
            bumpedTag="1.0.0"
          else
            versionParts=(${currentTag//./ })
            if [[ ${versionParts[2]} == 9 ]]; then
              bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
            elif [[ ${versionParts[1]} == 9 ]]; then
              bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
            else
              bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
            fi
          fi

          # Create release
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          releaseTitle=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}" | jq -r .title)
          response=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\": \"$bumpedTag\", \"name\": \"$releaseTitle\", \"body\": \"Release created from pull request.\"}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")

          echo "New release created with tag: $bumpedTag"
