name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and create release
        run: |
          # Bump version
          currentTag=$(git describe --abbrev=0 --tags)
          versionParts=(${currentTag//./ })  # Split version string into an array

          if [[ ${versionParts[2]} == 9 ]]; then
            # If third number is 9, increment second number and set third number to 0
            bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
          elif [[ ${versionParts[1]} == 9 ]]; then
            # If second number is 9, increment first number and set second number to 0
            bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
          else
            # Increment third number
            bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
          fi

          # Create release
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          releaseTitle=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}" | jq -r .title)
          response=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"tag_name\": \"$bumpedTag\", \"name\": \"$releaseTitle\", \"body\": \"Release created from pull request.\"}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")

          echo "New release created with tag: $bumpedTag"
