name: Tag Extraction

on:
  workflow_dispatch:

jobs:
  extract_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract current tag
        id: get_tag
        run: |
          currentTag=$(git describe --abbrev=0 --tags)
          echo "::set-output name=tag::$currentTag"

      - name: Use the extracted tag
        run: echo "Current tag is ${{ steps.get_tag.outputs.tag }}"

      - name: Bump tag version
        id: bump_version
        run: |
          currentTag=${{ steps.get_tag.outputs.tag }}
          versionParts=(${currentTag//./ })
          if [[ ${versionParts[2]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
          elif [[ ${versionParts[1]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
          else
            bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
          fi
          echo "::set-output name=bumped_tag::$bumpedTag"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.bumped_tag }}
          release_name: Release ${{ steps.bump_version.outputs.bumped_tag }}
          body: |
            This is the release for version ${{ steps.bump_version.outputs.bumped_tag }}.

      - name: Debug release response
        run: |
          echo "New release created with tag: ${{ steps.create_release.outputs.tag }}"
