name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and create release
        run: |
          # Bump version
          currentTag=$(git describe --abbrev=0 --tags --always)
          if [[ -z "$currentTag" ]]; then
            bumpedTag="1.0.0"
          else
            versionParts=(${currentTag//./ })
            if [[ ${versionParts[2]} == 9 ]]; then
              bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
            elif [[ ${versionParts[1]} == 9 ]]; then
              bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
            else
              bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
            fi
          fi

          # Create tag
          echo "New tag to be created: $bumpedTag"
          git tag "$bumpedTag"
          git push --tags

          # Create release
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          response=$(curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/releases" \
            --header "Authorization: Bearer $GITHUB_TOKEN" \
            --header 'Content-Type: application/json' \
            --data-raw "{
              \"tag_name\": \"$bumpedTag\",
              \"name\": \"Release $bumpedTag\",
              \"body\": \"Release created from push to main branch.\"
            }")
          
          echo "New release created with tag: $bumpedTag"
