name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Bump Tag and Release Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Taking the Latest Release Tag number
        id: releaseVersion
        run: |
          repository="$GITHUB_REPOSITORY"
          owner="${repository%%/*}"
          repo="${repository#*/}"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          echo "Release JSON: $release_json"
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          echo "Release_tag: Latest Tag is : $Release_tag"
          echo "::set-output name=Release_tag::$Release_tag"

      - name: Get Tag
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Bump tag version
        id: bump_version
        run: |
          currentTag=${{ steps.get_tag.outputs.tag }}
          versionParts=(${currentTag//./ })
          if [[ ${versionParts[2]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
          elif [[ ${versionParts[1]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
          else
            bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
          fi
          echo "::set-output name=bumped_tag::$bumpedTag"
        
      - name: Create release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=${{ steps.bump_version.outputs.bumped_tag }}
          repository="$GITHUB_REPOSITORY"
          owner="${repository%%/*}"
          repo="${repository#*/}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$owner/$repo/releases" \
            -d '{"tag_name":"v'"${version}"'","target_commitish":"main","name":"v'"${version}"'","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
