name: Bump Tag and Create Release

on:
  pull_request:
    branches:
      - main

jobs:
  bump-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current tag
        id: get_tag
        run: |
          repository="$GITHUB_REPOSITORY"
          owner="${repository%%/*}"
          repo="${repository#*/}"
          currentTag=$(curl -s "https://api.github.com/repos/$owner/$repo/tags" | jq -r '.[0].name')
          echo "::set-output name=tag::$currentTag"
          echo $currentTag

      - name: Bump tag version
        id: bump_version
        run: |
          currentTag=${{ steps.get_tag.outputs.tag }}
          versionParts=(${currentTag//./ })
          if [[ ${versionParts[2]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
          elif [[ ${versionParts[1]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
          else
            bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
          fi
          echo "::set-output name=bumped_tag::$bumpedTag"

      - name: Create GitHub Release
        id: create_release
        run: |
          repository="$GITHUB_REPOSITORY"
          owner="${repository%%/*}"
          repo="${repository#*/}"
          currentTag=${{ steps.get_tag.outputs.tag }}
          latestCommit=$(git log -1 --pretty=format:"%s")
          # Split the tag into version parts
          IFS='.' read -r -a versionParts <<< "$currentTag"
          # Increment the appropriate version part
          if [[ ${versionParts[2]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.${versionParts[1]}.0"
          elif [[ ${versionParts[1]} == 9 ]]; then
            bumpedTag="${versionParts[0]}.0.${versionParts[2]}"
          else
            bumpedTag="${versionParts[0]}.${versionParts[1]}.$((${versionParts[2]} + 1))"
          fi
          release_payload='{"tag_name":"'"$bumpedTag"'","target_commitish":"main","name":"'"$bumpedTag"'","body":"'"$latestCommit"'","draft":false,"prerelease":false,"generate_release_notes":false}'
          echo "Release payload: $release_payload"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$owner/$repo/releases" \
            -d "$release_payload"
          echo "::set-output name=tag::$bumpedTag"

      - name: Debug release response
        run: |
          echo "New release created with tag: ${{ steps.create_release.outputs.tag }}"
