name: Terraform CI

on:
  push:
    branches-ignore:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Validate Terraform code
        run: terraform validate

      - name: Format Terraform code
        run: terraform fmt -check